<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>disable</Nullable>
    <AssemblyName>Axiom</AssemblyName>
    <RootNamespace>Axiom</RootNamespace>
    <ApplicationIcon>axiom.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Version>1.9.6.1</Version>
    <Authors>Matt McManis</Authors>
    <Company>Axiom UI</Company>
    <Product>Axiom UI</Product>
    <Description>FFmpeg GUI for Windows</Description>
    <Copyright>Copyright (C) 2017-2025 Matt McManis</Copyright>

    <!-- Disable auto-generation of AssemblyInfo attributes (we have our own in Properties/AssemblyInfo.cs) -->
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HandyControl" Version="3.5.1" />
    <PackageReference Include="MahApps.Metro.IconPacks.Core" Version="6.2.1" />
    <PackageReference Include="MahApps.Metro.IconPacks.PhosphorIcons" Version="6.2.1" />
    <PackageReference Include="System.Management" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <!-- Embedded Resources -->
    <Resource Include="axiom.ico" />
    <Resource Include="Resources\Images\**\*.png" />
    <Resource Include="Resources\Images\**\*.jpg" />
    <Resource Include="Resources\Images\**\*.ico" />
  </ItemGroup>

</Project>
